spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?createDatabaseIfNotExist=true
    username: root
    password: root
  application:
    name: product-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update